sudo: 'required'

services:
  - 'docker'

before_install:
  - './.travis/main.sh'

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - './.travis/test.sh'
#  - 'make image'

# To have `DOCKER_USERNAME` and `DOCKER_PASSWORD`
# use `travis env set DOCKER_USERNAME ...`
# use `travis env set DOCKER_PASSWORD ...`
deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make push-image
  on:
    branch: master
